spring:
    datasource:
        url: jdbc:mysql://localhost:3306/taskdb
        username: root
        password: 1234

    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true      #show sql query in console(easy to debug)

        properties:            #match db version
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
